CREATE TABLE `mediacoes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nome` varchar(255) NOT NULL,
  `ctr1` varchar(255) NOT NULL,
  `desc1` varchar(255) DEFAULT NULL,
  `filial1` varchar(6) DEFAULT NULL,
  `ctr2` varchar(255) DEFAULT NULL,
  `desc2` varchar(255) DEFAULT NULL,
  `filial2` varchar(6) DEFAULT NULL,
  `ctr3` varchar(255) DEFAULT NULL,
  `desc3` varchar(255) DEFAULT NULL,
  `filial3` varchar(6) DEFAULT NULL,
  `ctr4` varchar(255) DEFAULT NULL,
  `desc4` varchar(255) DEFAULT NULL,
  `filial4` varchar(6) DEFAULT NULL,
  `valor1` decimal(10,2) NOT NULL,
  `valor2` decimal(10,2) DEFAULT NULL,
  `valor3` decimal(10,2) DEFAULT NULL,
  `valor4` decimal(10,2) DEFAULT NULL,
  `ultped4` varchar(6) DEFAULT NULL,
  `pedenv4` varchar(6) DEFAULT NULL,
  `pedenv3` varchar(6) DEFAULT NULL,
  `pedenv2` varchar(6) DEFAULT NULL,
  `pedenv1` varchar(6) DEFAULT NULL,
  `ultped3` varchar(6) DEFAULT NULL,
  `ultped2` varchar(6) DEFAULT NULL,
  `ultped1` varchar(6) DEFAULT NULL,
  `ultvalor4` decimal(10,2) DEFAULT NULL,
  `ultvalor3` decimal(10,2) DEFAULT NULL,
  `ultvalor2` decimal(10,2) DEFAULT NULL,
  `ultvalor1` decimal(10,2) DEFAULT NULL,
  `status1` varchar(50) NOT NULL DEFAULT 'Pendente',
  `status3` varchar(50) DEFAULT 'Pendente',
  `status4` varchar(50) DEFAULT 'Pendente',
  `diaenvio` int NOT NULL,
  `ctt` varchar(15) DEFAULT '+5562996005956',
  `email` varchar(255) DEFAULT NULL,
  `last_reset` date DEFAULT NULL,
  `DELETED` varchar(1) DEFAULT NULL,
  `user` varchar(255) NOT NULL,
  `notify` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12358 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci